### ISSUE TITLE
Data model with array objects

### ISSUE THREAD

**Issue by christianmls** [petersirka/jquery.bindings#2]
Hi, the plugins is fantastic, but I have a model:

```
{
pro1: '',
list:{
pro1: '',
pro2: '',
....
}
}
```

How I can set the binding on this?

**Comment by petersirka** [comment]
Hi @christianmls,
this plugin is deprecated for me, but I have written better library: <https://github.com/totaljs/jComponent>, try it 👍 

Maybe this is the answer for your question:
<https://github.com/petersirka/jquery.bindings#bindingsupdatemodel>
