### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by robsoncombr** [petersirka/jquery.bindings#4]
Hello,

I do not see updates like since 3 years ago, is this project live? Is it stable?

Thanks.

**Comment by petersirka** [comment]
Hi @robsoncombr, I have written a new and better library called jComponent -
 www.componentator.com. `jquery.bindings` works but I don't continue in development.

Thank you!

**Comment by robsoncombr** [comment]
Is community or someone else keeping it? I will check.

**Comment by robsoncombr** [comment]
Closing.
